#!/bin/bash
#
#count number of command line arguments
#
echo " Total number of cl arguments are $#"
echo " $0.sh is the script name"
echo " $1 is the first cl argument"
echo " $2 is the second cl argument"
echo " All of the cl arguments are : $*"
